### ISSUE TITLE
error from notiffany with ruby 2.2.0 on OSX Yosemite (darwin14.0)

### ISSUE THREAD

**Issue by klausinho** [guard/notiffany#13]
Don't know whether this issue is an notiffany error or Guard error. 
However, cause the error is raised by notiffany, I assume that here is the right place to report that issue.

Today I installed the latest version of Guard. When I try to start Guard, I get an error message generated by notiffany:

`/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/notiffany-0.0.6/lib/notiffany/notifier/base.rb:117:in '_check_host_supported': Unsupported platform "darwin14.1.0" (Notiffany::Notifier::Base::UnsupportedPlatform)`

Here's the referred config line from rbconfig.rb:

`CONFIG["host_os"] = "darwin14.1.0"`

**Comment by e2** [comment]
Thanks for the report.

Could you run `guard` with the `-d` option? 

It provides a little more debug messages from `Notiffany` - I'm pretty sure you're trying to enable/force a notifier that isn't supported on OSX, e.g. `rb_notify` is Windows-only, `libnotify` and `notifysend` are Linux/BSD-only.

**Comment by klausinho** [comment]
Argh, shame on me :-1: You were right, I tried to use libnotify on OSX. That was caused by copy and paste without exactly reading what I've pasted.

Sorry for the inconvenience! Eliminating the libnotify calls in my Guardfile makes it work.

**Comment by e2** [comment]
No shame in trying to copy a working config from somewhere else.

Shame for forcing libnotify in a project's `Guardfile` without detecting the os ;)

**Comment by patbl** [comment]
I encountered this error and spent about an hour trying to debug it before I figured out that the notifier was being set by a `.guard.rb` file in my home directory that I'd carelessly copied from my Linux computer. Just a heads-up in case someone else did the same thing.

**Comment by e2** [comment]
@patbl - would it help if Guard mentioned loading the file in debug mode?

**Comment by patbl** [comment]
@e2 I did run it in debug mode, so it probably would've helped.
