### ISSUE TITLE
Release version 0.1.2 or 0.2.0

### ISSUE THREAD

**Issue by eitoball** [guard/notiffany#37]
It would be really nice if you could release new version because some people who are working on [Ruby on Rails Tutorial](https://www.railstutorial.org/) have issues that are fixed in #35.

**Comment by rymai** [comment]
@eitoball Sure thing, I released 0.1.2:

- https://github.com/guard/notiffany/releases/tag/v0.1.2
- https://rubygems.org/gems/notiffany
