### ISSUE TITLE
Emacs notifier stops guard dead if emacs-server isn't running

### ISSUE THREAD

**Issue by r4v5** [guard/notiffany#6]
We have a few developers on our team who use Emacs and some who don't even have it installed on their machines.

We have had `notification :emacs` in our project's Guardfile for a while, and it would display a message but guard would continue running if Emacs (specifically, Emacs + Emacs-server) wasn't running.

Now, though, it hits the error on https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/emacs.rb#L51 and aborts.
```
14:45:52 guard.1         | /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier/emacs.rb:51:in `_check_available': Emacs client failed (Notiffany::Notifier::Base::UnavailableError)
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier/base.rb:58:in `initialize'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier/detected.rb:91:in `new'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier/detected.rb:91:in `add'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier.rb:102:in `block in initialize'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier.rb:101:in `each'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier.rb:101:in `initialize'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier.rb:42:in `new'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/notiffany-0.0.3/lib/notiffany/notifier.rb:42:in `connect'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/notifier.rb:11:in `connect'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard.rb:61:in `setup'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/commander.rb:32:in `start'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/cli/environments/valid.rb:16:in `start_guard'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/cli.rb:113:in `start'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/aruba_adapter.rb:32:in `execute'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/lib/guard/aruba_adapter.rb:19:in `execute!'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/gems/guard-2.11.1/bin/guard:11:in `<top (required)>'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/bin/guard:23:in `load'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-2.1.2@project/bin/guard:23:in `<main>'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-.1.2@project/bin/ruby_executable_hooks:15:in `eval'
14:45:52 guard.1         |      from /Users/r4v5/.rvm/gems/ruby-.1.2@project/bin/ruby_executable_hooks:15:in `<main>'
14:45:52 guard.1         | exited with code 1
```

**Comment by webhat** [comment]
I have the same issue or a similar with the :tmux and :growl notifiers.

--

Oplerno is built upon empowering faculty and students

-- 
Daniël W. Crompton <daniel.crompton@gmail.com>


<http://specialbrands.net/>

<http://specialbrands.net/>
http://specialbrands.net/

       <http://twitter.com/webhat> <http://www.facebook.com/webhat>
<http://plancast.com/webhat> <http://www.linkedin.com/in/redhat>
 FAB8 4200 587A 6BB2 9D64  9DB9 D9D8 7346 D4F7 B651

**Comment by e2** [comment]
I'm not exactly sure how to handle this perfectly.

The idea is: 
1. If you have no notifications set, it should use whatever it detects.
2. If you pass notifiers (in the `Guardfile`), it means the user *expects* those notifiers to work, and it's better to crash than to either silently fail or show a message that can be missed, etc.

So if people with emacs want emacs notifications, they should use the `~/.guard.rb` file, with e.g.:
```ruby
notification(:emacs, some_option: 'some value')
```
and not even bother including a `notification` clause in the `Guardfile` if you have a team.

`notification` is actually a user setting, really.

If there's any API in the guardfile to better "merge" user preferences with defaults, let me know about the use case.

**Comment by e2** [comment]
If you really want the emacs client to be set regardless (and work), then as a hack, you can "stub" the emacsclient to do nothing, e.g.

```ruby
def has_emacs
  # whatever
end

notification(:emacs, has_emacs ? {} : { client: '/bin/true' })
```

**Comment by e2** [comment]
I've added a small note in the wiki about not putting this in the `Guardfile`:
https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#notification

**Comment by r4v5** [comment]
We'd always specified notifications straight in the Guardfile. Removed them and it seems to be doing the right thing.

**Comment by e2** [comment]
I think technically this is a feature request for Guard itself. 

(Because maybe Guard should just catch the exception and do something, like show info about `~/.guard.rb` and exit.)

Or maybe the Notiffany README should just mention the exceptions?

I don't personally use notification (except `:tmux`), so please reopen if you have an idea on how this can be "fixed" in Notiffany - or if it's really a pain in the ass somehow.
